### ISSUE TITLE
Taskbar text color does not change

### ISSUE THREAD

**Issue by zechzhao** [malvinas2/ClassicThemeForWindows10#10]
HI

Thanks a lot for sharing this. 

Following the installation steps I managed to get most of them. Except for one thing: the taskbar text color still not fully black:

![image](https://user-images.githubusercontent.com/11520462/109375801-7871bc00-78b7-11eb-8030-8847a52e2088.png)

My task bar settings should be the same as yours:

![image](https://user-images.githubusercontent.com/11520462/109375830-ac4ce180-78b7-11eb-845f-778343ff4b3e.png)

Any chance to know what the problem is here?

Thanks

**Comment by malvinas2** [comment]
**Step 7 - Windows Settings** it should be: Under` Choose your default Windows mode`, select `Light`, not Dark.
