### ISSUE TITLE
Some questions regarding this project

### ISSUE THREAD

**Issue by Raj2032** [malvinas2/ClassicThemeForWindows10#17]
Hi I have some questions regarding this project:
1. On VirtualBox with Windows 7, if I used the Aero theme and if I switched to the classic theme, then it would use less RAM and when moving the windows around it would be smoother. Is this the same thing if I installed the classic theme for Windows 10?
2. Is this project still going on or is it abandoned?
3. Is it possible to disable animations such as closing etc?
4. Can I customise the theme to look like this:

![image](https://user-images.githubusercontent.com/29293830/169527176-0ef1107c-9cf2-423b-aa55-76635c688f70.png)

(image retrieved from here https://github.com/tomasz1986/classic2000)

**Comment by malvinas2** [comment]
1. I don't believe so, but maybe you can verify this using the task manager which shows the free available RAM. 
2. More or less still maintained. I have a few ideas of what could be improved, but I don't have the time to implement them.
3. Using Windows 10 go to the Simplify and personalise Windows section and click the toggle switch under Show animations in Windows to turn animated visual effects off.
4. Well, you would have to create your own theme.

**Comment by Raj2032** [comment]
Hi @malvinas2 Thanks for your response.

In regards to number `4` question, you know how on Windows 7 classic theme you can edit the background color of the window and everything, is this possible with your theme? Is this what you mean by "have to create your own theme"?

**Comment by malvinas2** [comment]
No, the problem is that since Windows 8, Microsoft has introduced a complete new user interface. 
Possibilies of customization are very limited since then. 
[https://www.askvg.com/how-to-access-advanced-appearance-settings-option-to-change-text-size-in-windows-8/](https://www.askvg.com/how-to-access-advanced-appearance-settings-option-to-change-text-size-in-windows-8/)

**Comment by Raj2032** [comment]
@malvinas2 Oh jeeze, well thanks anyways.

How hard is for me to modify your theme?

**Comment by malvinas2** [comment]
Programs to create a Visual Style ("Theme"): 
[https://www.vistastylebuilder.com/index.html](https://www.vistastylebuilder.com/index.html)
[https://github.com/nptr/msstyleEditor](https://github.com/nptr/msstyleEditor)

_> How hard is for me to modify your theme?_
The main problem is that the structure is nearly not documented at all by Microsoft ;-)

**Comment by Raj2032** [comment]
@malvinas2 Lol why wouldn't microsoft document on this.
