### ISSUE TITLE
Window look doesn't change

### ISSUE THREAD

**Issue by nerdislav** [malvinas2/ClassicThemeForWindows10#22]
Hello :)

I was just trying to install the theme, but no matter what I do, the window style remains the same as it was in the previous theme. The taskbar and start menu look like Windows XP, but window style doesn't change.

I have followed the instructions in the tutorial precisely, I believe.

**Comment by malvinas2** [comment]
Hello,

It only works properly up to and including Windows 10 November 2019 Update 1909.
An update from my side for newer Windows versions is not planned.
And I don't use it myself anymore. 
(originally I hoped someone would find the project here and continue it ;-)   )

**Comment by nerdislav** [comment]
Aw :( I would take it up if I had any clue as how to even begin xD Oh well, thanks anyway! At least my taskbar and start menu look nice :)
