### ISSUE TITLE
First icon of task bar hides behind start button

### ISSUE THREAD

**Issue by malvinas2** [malvinas2/ClassicThemeForWindows10#3]
In case the search icon and/or task view icon is hidden, the first icon of the task bar hides behind the start button.  
Respectively, if the search icon or task view icon is shown, they are hidden partly behind the start button. 
![taskbar](https://user-images.githubusercontent.com/25912063/96350329-a5b29000-10b5-11eb-81d0-b813a4546004.png)

**Comment by malvinas2** [comment]
A work-around to resolve this issue is adding an empty toolbar: 

1. Right-click an empty area of the taskbar, point to `Toolbars`, and then click `New toolbar`.
![1](https://user-images.githubusercontent.com/25912063/104850725-1a81aa00-58f1-11eb-99c6-bfd2f153b4fa.png)

2.  In the dialog box, create a new folder with a name of your choice, select it and and then click `Select Folder`. 
![2](https://user-images.githubusercontent.com/25912063/104850735-27060280-58f1-11eb-8715-3c6c9b812714.png)

3. Now you see a new toolbar with the text on the rightside of the task bar. To hide the text and program titles, right-click the toolbar, clear `Show Text` and `Show title`. 
![3](https://user-images.githubusercontent.com/25912063/104850742-2e2d1080-58f1-11eb-9297-3911aa756eb1.png)

4. Drag the toolbar to the leftside of the task bar. If you cannot move the toolbar, right-click the taskbar again, and make sure that the Lock the taskbar option is cleared. Tip: Move the cursor horizontally. 
![4](https://user-images.githubusercontent.com/25912063/104850772-5583dd80-58f1-11eb-9bf4-77d0174eaa79.png)
![5](https://user-images.githubusercontent.com/25912063/104850777-57e63780-58f1-11eb-8f77-89fa43d6b5cf.png)

5. Go to the taskbar and right-click on it to launch the menu. Disable the option of `Show Task View`. 
![6](https://user-images.githubusercontent.com/25912063/104850789-6896ad80-58f1-11eb-899e-ec7af9782186.png)

6. To remove the Search icon, right-click an empty area on the taskbar and go to Search on the menu, and there you have the option to disable it or just show the search icon. 
![7](https://user-images.githubusercontent.com/25912063/104850794-72201580-58f1-11eb-9d16-a156dcb4f88c.png)

7. Finish! 
![8](https://user-images.githubusercontent.com/25912063/104850803-7f3d0480-58f1-11eb-90e4-93c5049fbd8b.png)

**Comment by lonedfx** [comment]
Another way to fix is to increase the width of the Open-Shell\Skins\classic3small.bmp file (the black portion will be transparent, or you can make a png with transparency instead, i use 80x90 pixels and it looks just about perfect).
