### ISSUE TITLE
StartIsBack++ Start Menu and Taskbar won't install

### ISSUE THREAD

**Issue by leoghs** [malvinas2/ClassicThemeForWindows10#6]
Even when following instructions, nothing in StartIsBackCfg.exe happens. plz help

**Comment by malvinas2** [comment]
Hello, 

your error description is quite short... The file `classic3.msstyles` must be placed within `%programdir%/startisback/styles` and the bmp-pictures called `classicV2...` should be located in `%programdir%/startisback/orbs`.

**Comment by leoghs** [comment]
I have done that as stated in the instructions.
Here I have it in a Virtual Machine because I abandoned it on my Main PC. 
![image](https://user-images.githubusercontent.com/52174190/98580059-ba063900-22bf-11eb-9d3b-8287cdafcfdf.png)

**Comment by leoghs** [comment]
fixed it on my own
